### ISSUE TITLE
[shared-ini-file-loader] loadSharedConfigFiles is broken on empty value - regression since v2.0.13

### ISSUE THREAD

**Issue by xfournet** [awslabs/smithy-typescript#1015]
# Describe the bug
The utility `loadSharedConfigFiles` incorrecly prefix keys when previous key has an empty value.
In the example below, in latest version, the `region` key is incorrectly prefixed with `cli_pager.`

# Steps to reproduce
```js
// test.mjs
import { tmpdir } from "os";
import { mkdtemp, rm, writeFile } from "fs/promises";
import { loadSharedConfigFiles } from "@smithy/shared-ini-file-loader";

const tempDir = await mkdtemp(tmpdir());

const filepath = `${tempDir}/credentials`;
await writeFile(filepath, ``);

const configFilepath = `${tempDir}/config`;
await writeFile(
  configFilepath,
  `[profile dev]
cli_pager=  
region = us-east-2`
);

const sharedConfigFiles = await loadSharedConfigFiles({
  filepath,
  configFilepath,
});

console.log(JSON.stringify(sharedConfigFiles, null, 2));

await rm(tempDir, { recursive: true });
```

# Observed behavior

## v2.0.12 ✅ correct behavior
```json
{
  "configFile": {
    "dev": {
      "region": "us-east-2"
    }
  },
  "credentialsFile": {}
}
```

## v2.0.13 ❌ incorrect behavior
```json
{
  "configFile": {},
  "credentialsFile": {}
}
```

## v2.1.0 and v2.2.0 ❌ incorrect behavior
```json
{
  "configFile": {
    "dev": {
      "cli_pager.region": "us-east-2"
    }
  },
  "credentialsFile": {}
}
```

# Additional context
The regression comes from 60e88afe9349fa540c54741a1b17c608aa6adbd5 (#986) and then from aa86b3fe240164bd0ab0a7291e504fbc90270a63 (#989)

**Comment by trivikr** [comment]
As per the SDK reference for [file-format](https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html), the subsections appears after the main section. And that's how the JS SDK v3 currently reads the configuration.

A workaround will be to move `region` above subsection as follows:
```console
[profile dev]
region = us-east-2
cli_pager=  
```

In the meantime, I'll investigate if we can read values after subsections.

**Comment by xfournet** [comment]
@trivikr yes the documentation specify that subsettings should have one or many spaces before. That is workly perfectly with AWS CLI and JS SDK until v2.0.12

I'm rather waiting for a new release instead of using the workaround : it may be costly to identify all the files to be updated, and in some situation I may not have the required permission to update them promptly.
