### ISSUE TITLE
Publish to maven

### ISSUE THREAD

**Issue by sam-goodwin** [awslabs/smithy-typescript#103]
`smithy-typescript` is not available in maven. Is there an ETA on when this package will be made available for consumption?

**Comment by brendo-m** [comment]
Any update here?

**Comment by srchase** [comment]
We do intend to begin publishing `smithy-typescript`, however there aren't any specific dates to share yet.  We'll likely begin publishing a pre-GA version.

**Comment by JordonPhillips** [comment]
We've done a few maven releases, so you can access things. Like Chase mentioned though, these are still pre-GA releases
