### ISSUE TITLE
Smithy Codegen: gradlew breaks on Java version 14, resulting in codegen not working. 

### ISSUE THREAD

**Issue by alexforsyth** [awslabs/smithy-typescript#187]
Issue: Gradle does not work on java 14, resulting in the codegen quitting with an exception and not generating code.

Reproduction:
Using the newest version of Java (14), and gradle 6.5 running 
```
./gradlew :sdk-codegen:build
```
from the codegen directory in aws-js-sdk-v3 results in error:
``` 
"Could not initialize class org.codehaus.groovy.runtime.InvokerHelper"
```
This issue is also documented with gradle here: https://github.com/gradle/gradle/issues/12599, however the suggested fix if upgrading to 6.3+ does not clear the error. Downgrading to Java 11 fixes the issue.

**Comment by jmlavoier** [comment]
I had the same issue, I downgraded my Java to version 11 and started to work.

**Comment by Deep1307** [comment]
If you are working on an Android Application, Just go to the root folder of your android project, open gradle-wrapper.properties, and then
replace the distributionUrl with the line below
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip

This thing Worked for my project, Maybe It will help you too.

**Comment by mtdowling** [comment]
We've since upgraded to Gradle 7, which seems to have resolved this.
