### ISSUE TITLE
Generated TypeScript Client includes body for GET Request

### ISSUE THREAD

**Issue by davjohna** [awslabs/smithy-typescript#192]
I have a Smithy service definition containing a simple GET operation with no input shape (not sure if API Gateway traits could be relevant, if not, the operation is only the last three lines):

    @readonly
    @http(method: "GET", uri: "/sources")
    @aws.apigateway#integration(
      type: "aws",
      httpMethod: "POST",
      uri: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ServiceApiLambda}/invocations",
      credentials: "${ApiLambdaInvokeRoleArn}",
      requestTemplates: {
            "application/json": """
    {
      "requestId": "$context.extendedRequestId",
      "api": "ListLogSources",
      "requester": {
        "federatedUser": "$context.identity.cognitoAuthenticationProvider",
        "callerAccountId": "$context.identity.accountId"
      },
      "inputJson": "$util.escapeJavaScript($input.json('$'))"
    }"""
      },
      responses: {
        "default" : {
          "statusCode" : "200"
        },
        ".*errorType\":\"UnknownOperationException\".*": {
          "statusCode": "404",
          "responseTemplates" : {
            "application/json" : "#set ($errorMessageObj = $util.parseJson($input.path('$.errorMessage')))\n{\n  \"errorType\" : \"$errorMessageObj.errorType\",\n  \"message\" : \"$errorMessageObj.errorMessage\"\n}"
          }
        },
        ".*errorType\":\"UnauthorizedOperationException\".*": {
          "statusCode": "403",
          "responseTemplates" : {
            "application/json" : "#set ($errorMessageObj = $util.parseJson($input.path('$.errorMessage')))\n{\n  \"errorType\" : \"$errorMessageObj.errorType\",\n  \"message\" : \"$errorMessageObj.errorMessage\"\n}"
          }
        }
      }
    )
    operation ListLogSources {
        output: ListLogSourcesOutput
    }

Building this results in a JSON file with an operation that also has no input:

    "com.fooservice#ListSources": {
        "type": "operation",
        "output": {
            "target": "com.fooservice#ListSources"
        },
        "traits": {
            "smithy.api#http": {
                "method": "GET",
                "uri": "/sources",
                "code": 200
            },
            "smithy.api#readonly": {}
        }
    },

My service definition in that same JSON file has these traits:

    "aws.api#service": {
      "sdkId": "Foo",
      "arnNamespace": "execute-api",
      "cloudFormationName": "FooService",
      "cloudTrailEventSource": "execute-api.amazonaws.com"
    },
    "aws.auth#sigv4": {
      "name": "execute-api"
    },
    "aws.protocols#restJson1": {},
    "smithy.api#cors": {},
    "smithy.api#documentation": "The Foo Service",
    "smithy.api#title": "Foo"

I'm able to generate a client fine, but the problem occurs when I invoke this operation on the generated client. I get an error about GET requires not allowing a request body, and, sure enough, the generated client has this in the operation serializer (in "protocols/Aws_restJson1.ts"):

    let resolvedPath = "/sources";
    let body: any;
    body = "{}";

But I'm not sure how to make that go away. Looking [through the source](https://github.com/awslabs/smithy-typescript/blob/master/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java#L393) that I thought to be relevant didn't give me any clues either, but I'm not as familiar with it. Is this a bug, or did I misconfigure something?

**Comment by gosar** [comment]
The issue is from 2020. I think the generator has been changed at some point. If I try to reproduce this case now, it does not generate `body = "{}"`, it generates `body =""`. So I'll resolve this issue. Note there is another related issue regarding Content-Type with this use case - https://github.com/awslabs/smithy-typescript/issues/552. You can follow that if it's relevant to you.
