### ISSUE TITLE
Enable dependabot for automated dependency management

### ISSUE THREAD

**Issue by trivikr** [awslabs/smithy-typescript#220]
**Is your feature request related to a problem? Please describe.**
Automated Dependency Management is not enabled on smithy-typescript. Therefore, we don't get notified when dependencies get updated.

**Describe the solution you'd like**
Enable dependabot once Kotlin support is added in https://github.com/dependabot/dependabot-core/issues/2238

**Describe alternatives you've considered**
* Manually updating dependencies.
* Maintain a separate `build.gradle` just for dependabot support.
  * Pro: Dependabot will use `build.gradle` for updating dependencies.
  * Con: `build.gradle.kts` will still have to be manually updated.

**Comment by mtdowling** [comment]
Merged the related PR
