### ISSUE TITLE
Allow build tool to be configurable

### ISSUE THREAD

**Issue by JordonPhillips** [awslabs/smithy-typescript#347]
Currently generated packages have an implicit dependency on yarn because a number of scripts call out to it, but yarn isn't listed in the dependencies. Ideally one of the following things should happen:

* [`yarn` should be added as a dependency](https://github.com/awslabs/smithy-typescript/pull/343)
* The script runner should be configurable

A reasonable take would be to just use npm by default and make it configurable from there. You can use `packageJson` in the smithy config to override things now. That might be a reasonable way to handle changing to something else honestly.

**Comment by alexforsyth** [comment]
You're right we don't recommend yarn (or any package manager) in particular, we're looking at a trying to configure this or worst case default to npm

**Comment by alexforsyth** [comment]
There's a few other workspace issues we might have to think about. Like jest, lerna, whatever
