### ISSUE TITLE
Feature request: support @httpApiKeyAuth with scheme

### ISSUE THREAD

**Issue by glb** [awslabs/smithy-typescript#453]
In response to https://github.com/awslabs/smithy/issues/872, https://github.com/awslabs/smithy/pull/893 added support for describing services that require a custom scheme value in the `Authorization` header; for example:

```
    @httpApiKeyAuth(scheme: "ApiKey", name: "Authorization", in: "header")
     service WeatherService {
         version: "2017-02-11",
     }
```

if the `Authorization` header is supposed to look like `Authorization: ApiKey {value}`. The folks there [said](https://github.com/awslabs/smithy/issues/872#issuecomment-941173568) that opening an issue here to request support would be the best next step to building an SDK that can interact with a service like this.

Searching through this repository I wasn't able to find _any_ references to `auth` or `authorization`, so I'm not sure where to start. Opening this issue to start the conversation.

**Comment by JordonPhillips** [comment]
Right now the only auth that's implemented for smithy-typescript is AWS's sigv4 auth: https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPlugin.java

To implement api key auth, you'd need to write a plugin to handle it much like that. I'm not sure when we'd be getting around to doing this, but if you want to tack a shot at it then we'd be happy to review.

**Comment by glb** [comment]
Thanks for the pointer @JordonPhillips . I'll try to figure it out, will quite likely have questions.

**Comment by glb** [comment]
OK @JordonPhillips @mtdowling, I'm back with the questions I promised 🙂:

1. It looks like the plugin needs to add a field to the config interface (the API key) and then create / inject a middleware handler into the client. I think that means I need to implement `addConfigInterfaceFields` and `getClientPlugins`. Is that right-ish? The first one seems pretty straightforward, the second is a bit more opaque. I'll try to dig into what's going on there but will likely have another layer of questions when I get into that.
2. My code builds, but next how do I register my new plugin so that it gets invoked when doing codegen? It looks like the `AddAwsAuthPlugin` is listed in a manifest in `aws-sdk-js-v3` which I assume is read somehow/somewhere; that doesn't seem to be appropriate in this case.
3. This may seem like a super-basic question, but I haven't touched Java in >4 years, so: how do I do a real test? I've got a model file that I think has the right content, so do I just run `gradle publishToMavenLocal` in this repo and then do a `gradle build` in my model repo?

I'll keep digging but thought I'd get these questions out there.

**Comment by glb** [comment]
Update: I think I've gotten very close to where I want. I don't particularly love the idea of having to publish a separate middleware module to set a header (though I have seen that [there's already one in the AWS SDK to set the Host header](https://github.com/aws/aws-sdk-js-v3/blob/b0e1422630bbdc6842f7b91629d1ff66693e0fde/codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AwsDependency.java#L54)), so am going to see what I can figure out so that `getHttpApiKeyAuthPlugin` can be an inline function. Is that a step too far?

```text
commands/ListThingsCommand.ts
25:import { getHttpApiKeyAuthPlugin } from "fake-hackery";
49:    this.middlewareStack.use(getHttpApiKeyAuthPlugin(configuration));
```

**Comment by glb** [comment]
Update: I've figured out how to use `writeAdditionalFiles` to write the middleware module, and I think I've got everything relevant to the plugin working. No idea yet if the actual middleware works or if the generated typescript code is good.

Two parallel paths of investigation next:
1. Learn enough TypeScript to try to use the generated client.
2. Figure out why I'm getting this error and how to fix it because the generated client doesn't actually know how to serialize requests:

   ```text
   Unable to find a protocol generator for example.com#Example: The example.com#Example service supports the following unsupported protocols [aws.protocols#restJson1]. The following protocol generators were found on the class path: []
   ```

**Comment by glb** [comment]
Next layer of the onion: I'm trying to use
```
   .pluginFunction(Symbol.builder().namespace("./middleware/HttpApiKeyAuth", "/")
                                   .name("getHttpApiKeyAuthPlugin")
                                   .build())
```

but that's translating into `... = require("../../middleware/HttpApiKeyAuth");` in operations and `... = require("../middleware/HttpApiKeyAuth")` in the client; these don't work but taking out the extra `..` manually after codegen does. Need to figure out what's going on in the codegen there and how to fix it.

Had a brief hiccup around `endpoint` but figured out that I can just pass it in to the client constructor like in the normal AWS SDK and it's ... actually connecting and making a request!

Also need to figure out how to change these; hopefully it's just something I shouldn't have in my model or something I'm missing:

```
x-amz-user-agent: aws-sdk-js/0.0.1
user-agent: aws-sdk-js/0.0.1 os/darwin/21.1.0 lang/js md/nodejs/14.17.5
amz-sdk-invocation-id: aa728ff4-e7f2-4b48-9923-20d0b966bf79
amz-sdk-request: attempt=1; max=3
```

So close!

**Comment by glb** [comment]
Figured out the correct magic by looking at other places where things were being imported:

```
                .pluginFunction(Symbol.builder()
                    .namespace("./" + CodegenUtils.SOURCE_FOLDER + "/middleware/HttpApiKeyAuth", "/")
                    .name("getHttpApiKeyAuthPlugin")
                    .build())
```

makes the imports relativize properly.

The AWS SDK headers are an unrelated problem that I'm choosing to ignore for now.

Next step: tests. Will look at [AddAwsAuthPluginTest.java](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/smithy-aws-typescript-codegen/src/test/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPluginTest.java) for inspiration.

**Comment by glb** [comment]
Initial tests for the Java code are done. Need to learn how to write tests for the middleware. Back to [AddAwsAuthPlugin.java:223](https://github.com/aws/aws-sdk-js-v3/blob/b0e1422630bbdc6842f7b91629d1ff66693e0fde/codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsAuthPlugin.java#L223) to see how tests get added to the client and [sts-client-defaultRoleAssumers.spec.ts](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/smithy-aws-typescript-codegen/src/main/resources/software/amazon/smithy/aws/typescript/codegen/sts-client-defaultRoleAssumers.spec.ts) for examples!

**Comment by glb** [comment]
So `sts-client-defaultRoleAssumers.spec.ts` wasn't a great source of applicable testing examples but [middleware-host-header/src/index.spec.ts](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/middleware-host-header/src/index.spec.ts) really was. Tests seem to do the right thing now.

**Comment by glb** [comment]
I intend to create a draft PR in the morning. Anything I should keep in mind other than what's in [CONTRIBUTING.md](https://github.com/awslabs/smithy-typescript/blob/main/CONTRIBUTING.md) and looking at existing PRs for examples?

**Comment by glb** [comment]
Draft PR created for the next phase of discussion. Happy to mark this as "ready for review" if that's your workflow preference. The PR is awaiting maintainer approval to run the GitHub workflow.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/372794/145068058-7a5cb362-ec06-4344-95e1-7b5617a1b90a.png">

Looking forward to your comments!
