### ISSUE TITLE
Document type not allowing null values

### ISSUE THREAD

**Issue by eduardomourar** [awslabs/smithy-typescript#517]
After defining the following Smithy model:

<details>
  <summary>Smithy model</summary>

```
namespace smithy.example

string ForecastName
document WeatherData

operation UpdateForecast {
    input: ForecastInput,
    output: ForecastOutput
}

structure ForecastInput {
    @required
    forecastName: ForecastName,

    @required
    weather: WeatherData,
}

structure ForecastOutput {
    @required
    forecastName: ForecastName,

    @required
    weather: WeatherData,
}
```

</details>

For the `document` shape, the `null` values are being removed from the input as well as the output during serialization logic. The Smithy generated server SDK contains the following code:

```typescript
  const data: { [key: string] : any } = __expectNonNull((__expectObject(await parseBody(output.body, context))), "body");
  if (data.weather !== undefined && data.weather !== null) {
    contents.weather = deserializeAws_restJson1RequestPayload(data.weather, context);
  }
```

I am confused because it is allowed in the type definition [here](https://github.com/aws/aws-sdk-js-v3/blob/1e3faa1976a5119dcc985c8f513833e3d01fe3dc/packages/types/src/shapes.ts#L12), and in the Smithy documentation [here](https://awslabs.github.io/smithy/1.0/spec/core/type-refinement-traits.html#box-trait), it is stated:
> Boolean, byte, short, integer, long, float, and double shapes are only considered boxed if they are marked with the box trait. All other shapes are always considered boxed.

Therefore, I would expect the user to be able to pass `null` as a valid document without a problem, right?

**Comment by adamthom-amzn** [comment]
Using the 0.10.0 generator, I am able to send and receive null values inside documents without issue.

As for documents themselves that are null, this is not controlled by document serialization behavior, but by the restJson1 protocol. restJson1 does not serialize members of any structure that are null. Instead, it omits the member entirely. This is true for members of any type. This behaves as I expect with a top-level document member of input and output structures in my testing - if I specify null for the value, it is omitted altogether when serialized to the wire.
