### ISSUE TITLE
Use default Error object from JavaScript in the server

### ISSUE THREAD

**Issue by eduardomourar** [awslabs/smithy-typescript#518]
Is there a particular reason that the generated errors from Smithy are not extending the Error class as specified in [the ECMAScript standard](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-error-objects)? Obviously considering that a `message` property is specified and it is marked as required.

Otherwise, we do not have stack traces as part of instance and we cannot check using `instanceof` against a common parent class. There is a suggestion of implementation in the MDN documentation [here](https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/error#custom_error_types).

**Comment by adamthom-amzn** [comment]
As of https://github.com/awslabs/smithy-typescript/pull/502 the exceptions will be a subtype of Error (except for the internal errors we do not anticipate users throwing directly). Those should be available in the next generator release, probably 0.10.0. I don't have an ETA for that version at present.

**Comment by gosar** [comment]
0.10.0 has released on 2022-03-02.
