### ISSUE TITLE
Question: IDL 2.0 roadmap?

### ISSUE THREAD

**Issue by RossWilliams** [awslabs/smithy-typescript#536]
There is now a branch for [Smithy IDL 2.0 RC1](https://github.com/awslabs/smithy/tree/idl-2.0-rc-1), but I do not see a public branch for this repo which contains IDL 2.0 support.

Is support for this being work on in private? Or has the work not yet begun?

Do you foresee the work towards 2.0 support being conducted via public branches with community involvement, or is it more likely to land in a near-complete state?

**Comment by gosar** [comment]
Thank you for your interest in Smithy IDL 2.0. Smithy IDL 2.0 is being worked on in https://github.com/awslabs/smithy/tree/idl-2.0. Here is the design doc - https://github.com/awslabs/smithy/blob/idl-2.0/designs/default-zero-value.md. 

Current status: We have been working on Smithy IDL 2.0 for some time now. We're putting the final touches and hope to release it in mid-late May.

**Comment by RossWilliams** [comment]
Hi, sorry I'm specifically asking about TypeScript codegen support for IDL 2.0. I am aware that Smithy itself is nearing completion.

**Comment by RossWilliams** [comment]
thanks, I realised my attempt to fix this on the server side ran into issues with types coming from @aws-sdk and would be a larger piece of work than it was worth vs just patching packages.
