### ISSUE TITLE
Codegen doesn't work on Windows

### ISSUE THREAD

**Issue by kiiadi** [awslabs/smithy-typescript#568]
When running the code generator on windows module namespaces use the Windows path format (e.g. `from 
".commands\OperationNameCommand"`) because of extensive use of `Path.get` / `Path.relativize`:

Examples:
https://github.com/awslabs/smithy-typescript/blob/main/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java#L426
https://github.com/awslabs/smithy-typescript/blob/main/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ImportDeclarations.java#L143

Also this fails to run codeGen because `modelPrefix` is ".\src\models" which is an invalid regex:
https://github.com/awslabs/smithy-typescript/blob/main/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java#L449

**Comment by srchase** [comment]
Fixed in #661.
