### ISSUE TITLE
Generated clients send incorrect "Accept: */*" header

### ISSUE THREAD

**Issue by jamesls** [awslabs/smithy-typescript#570]
For context, my use case is to try and get a smithy-typescript client (in the browser) to talk to a smithy-rs service that are both generated from the same smithy model.  I'm *almost* there, except that I'm running into an issue where the smithy-rs service is rejecting requests from the generated client because it sends an `Accept: */*` in its request.  See https://github.com/awslabs/smithy-rs/issues/1544.

Digging into it more, the service side validation comes from this PR [here](https://github.com/awslabs/smithy-rs/pull/1424), which cites the smithy protocol tests, and if I'm reading [the tests](https://github.com/awslabs/smithy/blob/HEAD/smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-accept.smithy) correctly, it seems like it's doing the right thing by requiring `Accept: application/json` for rest-json or allowing it to be omitted (I think).

The headers sent from the generated client are:

```
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
amz-sdk-invocation-id: 2d5e2fc9-f69e-4ffe-bede-d463d995d2ea
amz-sdk-request: attempt=1; max=3
Connection: keep-alive
content-type: application/json
Host: (... redacted ...)
Origin: (... redacted ...)
Referer: (... redacted ...)
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
x-amz-user-agent: aws-sdk-js/0.1.0 os/macOS/10.15 lang/js md/browser/Firefox_91.0 api/(redacted)/0.1.0
```

Regardless of what end the fix is on, it seems like the smithy-typescript clients should be able to talk to the smithy-rs services.

**Comment by adamthom-amzn** [comment]
There is no reason for a Smithy service to have more strict handling of `Accept` than the HTTP RFCs describe. `*/*` is a perfectly valid value for this.

**Comment by jamesls** [comment]
I suppose there's nothing explicitly called out in those protocol tests for `Accept: */*` (it's only explicit that you can't send unsupported media types) but it's also not clear what the expected behavior should be if the clients send `Accept: */*` and gets back something besides `application/json` or any of the other supported [content types](https://awslabs.github.io/smithy/1.0/spec/aws/aws-restjson1-protocol.html#content-type) in the `restJson1` protocol.

**Comment by gosar** [comment]
Seems like this is addressed by https://github.com/awslabs/smithy/pull/1365 and https://github.com/awslabs/smithy-rs/issues/1544. Resolving.
