### ISSUE TITLE
Tiny typo in blog post

### ISSUE THREAD

**Issue by pklewing** [awslabs/smithy-typescript#578]
just spotted a tiny regex typo in the blog post 
https://aws.amazon.com/blogs/devops/smithy-server-and-client-generator-for-typescript/
@pattern(“^[a-zA-Z0-9]$”) should be 
@pattern(“^[a-zA-Z0-9]*$”)

Other than that: great work!

**Comment by cmoher** [comment]
Thank you for reporting this.  This is now fixed on the blog post.
