### ISSUE TITLE
Set initial version to 0.1.0-preview.1

### ISSUE THREAD

**Issue by trivikr** [awslabs/smithy-typescript#79]
**Describe the bug**
The client versions were set to "1.0.0", and had to be manually edited to "0.1.0-preview.1" https://github.com/aws/aws-sdk-js-v3/pull/666

**To Reproduce**
Run CodeGen on aws-sdk-js-v3 by following instructions in https://github.com/aws/aws-sdk-js-v3/tree/smithy-codegen/codegen/sdk-codegen

**Expected behavior**
* The version should be set to **0.1.0-preview.1** as of now
* lerna will manage version numbers for clients in future, we can come up with a different system setup then

**Comment by kstich** [comment]
This is handled by a [setting given to the `typescript-codegen` here](https://github.com/awslabs/smithy-typescript/blob/master/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java#L75).

For `aws-sdk-js-v3`, it is defaulted and can be modified in [the `generate-smithy-build` task in here](https://github.com/aws/aws-sdk-js-v3/blob/smithy-codegen/codegen/sdk-codegen/build.gradle.kts#L57).

**Comment by trivikr** [comment]
Closing, as issue will be tracked in https://github.com/aws/aws-sdk-js-v3/issues/672
