### ISSUE TITLE
Duplicate identifier in models/index.ts

### ISSUE THREAD

**Issue by trivikr** [awslabs/smithy-typescript#80]
**Describe the bug**
A "`Duplicate identifier`" error is thrown in some generated clients:
* https://github.com/aws/aws-sdk-js-v3/issues/664#issuecomment-571402554
* https://github.com/aws/aws-sdk-js-v3/issues/664#issuecomment-571407651

**To Reproduce**
* generate iot client using model defined in https://github.com/aws/aws-sdk-js-v3/blob/65740e3548fbacf93ff9b07fc379fe3731c622c1/codegen/sdk-codegen/aws-models/iot.2015-05-28.json 
* Run `tsc` on it (TypeScript compilation)
* Notice that the following error is thrown:
```console
models/index.ts(10350,3): error TS2300: Duplicate identifier 'CONTINUOUS'.
models/index.ts(10351,3): error TS2300: Duplicate identifier 'SNAPSHOT'.
models/index.ts(11255,3): error TS2300: Duplicate identifier 'CONTINUOUS'.
models/index.ts(11256,3): error TS2300: Duplicate identifier 'SNAPSHOT'.
```

**Expected behavior**
TypeScript compilation succeeds without any issue

**Comment by trivikr** [comment]
This happens because the enum `TargetSelection` is exported twice in the [client-iot/models/index.ts](https://github.com/aws/aws-sdk-js-v3/blob/65740e3548fbacf93ff9b07fc379fe3731c622c1/clients/client-iot/models/index.ts)
* First time https://github.com/aws/aws-sdk-js-v3/blob/smithy-codegen/clients/client-iot/models/index.ts#L10349
* Second time https://github.com/aws/aws-sdk-js-v3/blob/smithy-codegen/clients/client-iot/models/index.ts#L11254

**Comment by trivikr** [comment]
This happens because the same `TargetSelection` is defined under `om.amazonaws.iot.laser` as well as `com.amazonaws.iot.otamanager`

Model: https://github.com/aws/aws-sdk-js-v3/blob/65740e3548fbacf93ff9b07fc379fe3731c622c1/codegen/sdk-codegen/aws-models/iot.2015-05-28.json#L21144,L21169

Proposed solution: break down models/index.ts into smaller files as suggested in https://github.com/awslabs/smithy-typescript/issues/81

**Comment by mtdowling** [comment]
> Proposed solution: break down models/index.ts into smaller files as suggested in #81

That is immaterial to this issue. This issue is caused by stripping namespaces during code generation.
