### ISSUE TITLE
[Suggestion] Break down model/index.ts into smaller files

### ISSUE THREAD

**Issue by trivikr** [awslabs/smithy-typescript#81]
**Is your feature request related to a problem? Please describe.**
* Some `models/index.ts` are slow (on GitHub/VSCode) because of their large size.
* Example file [`client-iot/models/index.ts`]() with 18K lines of code takes 30+ seconds to load on GitHub

<details>
<summary>Screen recording</summary>

![large-models-index](https://user-images.githubusercontent.com/16024985/71910224-6a4a6480-3126-11ea-983b-4df3078b1fca.gif)

</details>

* The file is slow to browse on VSCode too

<details>
<summary>Screen recording</summary>

![vscode-model-index](https://user-images.githubusercontent.com/16024985/71910237-6e768200-3126-11ea-8dd3-dad0b89b1ec3.gif)

</details>

* Since these files are CodeGen, SDK developers are not going to edit them directly. But they'll be browsing them to examine requests and responses. Also, AWS SDK users will be browsing them while examining types.

**Describe the solution you'd like**
Break `models/index.ts` into multiple files

**Describe alternatives you've considered**
Work with existing large sized `models/index.ts` files

**Comment by AllanFly120** [comment]
Plus one on this. `models/index.ts` constains a lot of [IIFEs](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) which cannot be tree-shaked. It's bad for clients that have a lot of models.

**Comment by mtdowling** [comment]
We intentionally put all models into a single file to reduce the number of files we need to write. For example, the old JS generators created a new file for each shape, resulting in sometimes thousands of files per service. Reducing the number of files we write speeds up codegen, makes it easier to find where generated files are placed, and I suspect makes it faster to clone the repo.

Is there a suggestion that we can take that still creates a minimum amount of files but reduces the number of models per file?

**Comment by AllanFly120** [comment]
@mtdowling We don't to implement this now, I'd rather see it as an optimization. The bundler's tree shaking can pick up whatever is required from `index.ts` and get rid of others. This means if we re-export useful things from `models`(which we should have), user only need to import things in `models` from client package root. Then they don't need to worry about the internal file structure of the client packages. In fact, we don't plan to support any API that is not re-exported from root `index.ts`

I have confirmed that splitting the models file will help with tree shaking and benefit bundle size

**Comment by mtdowling** [comment]
I think we forgot to close this one out. Models are chunked into separate files now.
