### ISSUE TITLE
api-gateway: 'methodSettings' does not exist in type 'Stage'

### ISSUE THREAD

**Issue by trivikr** [awslabs/smithy-typescript#82]
**Describe the bug**
* Generated client-api-gateway has TypeScript error `'methodSettings' does not exist in type 'Stage'`
* Refs: https://github.com/aws/aws-sdk-js-v3/issues/664#issuecomment-571405438

**To Reproduce**
* `git clone https://github.com/aws/aws-sdk-js-v3.git --branch smithy-codegen`
* Open `clients/client-api-gateway/protocols/Aws_restJson1_1.ts` in VSCode or any other editor with TypeScript support
* Code: https://github.com/aws/aws-sdk-js-v3/blob/65740e3548fbacf93ff9b07fc379fe3731c622c1/clients/client-api-gateway/protocols/Aws_restJson1_1.ts#L8715

**Expected behavior**
No TS errors are thrown

**Comment by srchase** [comment]
This line in the generated code is the issue: https://github.com/aws/aws-sdk-js-v3/blob/65740e3548fbacf93ff9b07fc379fe3731c622c1/clients/client-api-gateway/models/index.ts#L7331

re-running the codegen now gives the correct comment.
