### ISSUE TITLE
client-s3-control fails with "Cannot redeclare block-scoped variable 'keyNode'"

### ISSUE THREAD

**Issue by trivikr** [awslabs/smithy-typescript#97]
Refs: https://github.com/aws/aws-sdk-js-v3/pull/728#issuecomment-573994949

**Comment by trivikr** [comment]
A PR just for the client s3-control https://github.com/aws/aws-sdk-js-v3/pull/729#issuecomment-574012475

**Comment by srchase** [comment]
https://github.com/aws/aws-sdk-js-v3/pull/729 can be fixed now with the updated codegen in https://github.com/aws/aws-sdk-js-v3/pull/730
